Use individual files as arguments instead of a source directory
This is more flexible and makes the --test option obsolete.

diff --git a/tc2dracor b/tc2dracor
--- a/tc2dracor
+++ b/tc2dracor
@@ -8,24 +8,22 @@ usage () {
 FreDraCor conversion.
 Transforms original source files in parallel processes.
 
-Usage: $0 [options] SOURCE_DIR [TEI_DIR]
+Usage: $0 [options] SOURCE_FILE [SOURCE_FILE...]
 
 OPTIONS:
-  -n, --num N     number of exist containers to spin up (default: 2)
-  -p, --port N    port number of eXist database to use
-  -D, --docker    use docker even when podman is available
-  -P, --progress  enable a progress bar
-  -t, --test      run only on a few files
-  -v, --verbose   show more detailed output
-  -h, --help      show this message
+  -n, --num N       number of exist containers to spin up (default: 2)
+  -p, --port N      port number of eXist database to use
+  -o, --output DIR  directory to write files to (default: ./tei)
+  -D, --docker      use docker even when podman is available
+  -P, --progress    enable a progress bar
+  -v, --verbose     show more detailed output
+  -h, --help        show this message
 
 EOF
 }
 
-# pick only XML files from the source directory
 list_sources () {
-  opts=$1
-  ls $opts $SOURCE_DIR | grep -i '\.xml$'
+  for f in $SOURCES; do echo $f; done
 }
 
 # store logs from containers
@@ -77,22 +75,17 @@ process_slice () {
   port=${PORTS[$n]}
   [ -z $PROGRESS ] && echo "processing files on localhost:$port ($instance)"
   for i in $(seq $instance ${#PORTS[@]} $num); do
-    if [ ! -z $TEST_MODE ]; then
-      # take the smallest files in test mode
-      file=$(list_sources -Sr | head -$i | tail -1)
-    else
-      # alphanumeric order
-      file=$(list_sources | head -$i | tail -1)
-    fi
-
-    name=$(echo $file | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')
-
-    [ -z $PROGRESS ] && echo "$instance $i $file -> $name"
+    file=$(list_sources | head -$i | tail -1)
+    file_name=$(basename $file)
+    dracor_name=$(echo $file_name | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')
+  
+    [ -z $PROGRESS ] && echo "$instance $i $file_name -> $dracor_name"
+  
     curl -s -X POST \
       -H 'Content-Type: application/xml' \
-      -H "X-Filename: $file" \
-      -o $WORK_DIR/tei/$name \
-      --data-binary @$SOURCE_DIR/$file \
+      -H "X-Filename: $file_name" \
+      -o $WORK_DIR/tei/$dracor_name \
+      --data-binary @$file \
       http://admin:@localhost:$port/exist/rest/db/tc2dracor/tc2dracor.xq
   done
 }
@@ -116,11 +109,6 @@ while (( "$#" )); do
       PROGRESS=yes
       shift
       ;;
-    -T|--test)
-      TEST_MODE=yes
-      echo "TEST MODE ENABLED"
-      shift
-      ;;
     -v|--verbose)
       VERBOSE=yes
       shift
@@ -138,6 +126,10 @@ while (( "$#" )); do
         echo "Error: Argument for $1 is missing" >&2
         exit 1
       fi
+      ;;
+    -o|--out|--output)
+      OUT_DIR=$2
+      shift 2
       ;;
     -p|--port)
       if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
@@ -176,35 +168,36 @@ elif [[ -z $(which docker) ]]; then
 fi
 
 BASE_DIR=$(dirname $0)
+OUT_DIR=${OUT_DIR:-$BASE_DIR/tei}
 
-SOURCE_DIR=${1:-$BASE_DIR/../theatre-classique/xml}
-TEI_DIR=${2:-$BASE_DIR/tei}
+SOURCES=$@
 
-if [[ ! -d $SOURCE_DIR ]]; then
-  echo "Source directory '$SOURCE_DIR' not available!"
-  echo "Make sure to checkout https://github.com/dracor-org/theatre-classique next to fredracor."
-  echo
+if [[ -z $SOURCES ]]; then
+  usage
   exit 1
 else
   NUM_SOURCES=$(list_sources | wc -l | sed -E 's/^ +//')
-  echo "Using original files from: $SOURCE_DIR"
-  echo "Original files found: $NUM_SOURCES"
+  [ -z $VERBOSE ] || echo "Number of source files: $NUM_SOURCES"
 fi
 
-if [[ ! -d $TEI_DIR ]]; then
-  echo "Missing TEI directory!"
-  echo "Usage: $0 [options] source_dir tei_dir"
+if [[ ! -d $OUT_DIR ]]; then
+  echo "Missing output directory!"
+  echo
+  usage
   exit 1
 else
-  echo "Target directory: $TEI_DIR"
+  [ -z $VERBOSE ] || echo "Output directory: $OUT_DIR"
 fi
 
-# check git status of TEI_DIR
-cd $TEI_DIR
-if [[ $(git status --porcelain --untracked-files=no .) != '' ]]; then
+# check git status of OUT_DIR
+cd $OUT_DIR
+dotgit=$(git rev-parse --git-dir 2> /dev/null)
+if [[ -n "$dotgit" ]] && \
+   [[ $(git status --porcelain --untracked-files=no .) != '' ]]
+then
   echo
-  echo "Uncommitted changes in TEI directory ($TEI_DIR)!"
-  echo 'Please make sure to commit or revert any changes before running a new conversion.'
+  echo "Uncommitted changes in output directory $OUT_DIR!"
+  echo "Please commit, stash or revert any changes first."
   echo
   exit 1
 fi
@@ -287,12 +280,7 @@ done
 
 [ -z $VERBOSE ] || echo "$(date +'%T') :: processing $NUM_SOURCES files"
 
-if [ ! -z $TEST_MODE ]; then
-  num=23 # take only a few files
-else
-  num=$NUM_SOURCES
-fi
-
+num=$NUM_SOURCES
 numports=${#PORTS[@]}
 
 for i in $(seq 1 $numports); do
@@ -308,7 +296,7 @@ wait > /dev/null
 [ -z $VERBOSE ] || echo "$(date +'%T') :: transformation done"
 
 # import new files to THIS repo
-cp $WORK_DIR/tei/*.xml $TEI_DIR/
+cp $WORK_DIR/tei/*.xml $OUT_DIR/
 
 # terminate
 log
